version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: node_modules
      - run:
          name: deploy
          command: ./deploy.sh
      - save_cache:
          key: node_modules
          paths:
            - node_modules

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master